'server-only';

import { prisma } from '@/lib/db';
import { validateSQL } from './sql-validator';

export type SQLExecResult =
  | { ok: true; rows: Record<string, unknown>[]; sql: string }
  | { ok: false; reason: string; sql?: string };

/**
 * Validates then executes a SELECT SQL query generated by the planner LLM.
 * All execution is read-only (SELECT only enforced by validateSQL).
 */
export async function executePlannerSQL(
  rawSql: string,
  role: string
): Promise<SQLExecResult> {
  // 1. Validate & sanitize
  const validation = validateSQL(rawSql, role);
  if (!validation.safe) {
    return { ok: false, reason: validation.reason };
  }

  const { sql } = validation;

  // 2. Execute
  try {
    const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(sql);
    // Prisma returns BigInt for COUNT() — serialize to number
    const serialized = rows.map(row =>
      Object.fromEntries(
        Object.entries(row).map(([k, v]) => [
          k,
          typeof v === 'bigint' ? Number(v) : v,
        ])
      )
    );
    return { ok: true, rows: serialized, sql };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // Strip internal Postgres path details from the error
    const clean = msg.replace(/\n[\s\S]*/m, '').slice(0, 200);
    return { ok: false, reason: `Database error: ${clean}`, sql };
  }
}
