// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
if (process.env.NODE_ENV !== 'production') {
  try {
    require("dotenv").config();
  } catch (e) {
    // Ignore
  }
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
