apiVersion: apps/v1
kind: Deployment
metadata:
  name: sees-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sees-postgres
  template:
    metadata:
      labels:
        app: sees-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sees-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sees-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: sees-secrets
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: sees-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sees-postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30543
  selector:
    app: sees-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sees-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
