name: Deploy Application

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infra/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-east-1'
      ECR_REPOSITORY: 'sees-platform-app'
      ECS_SERVICE: 'sees-platform-service'
      ECS_CLUSTER: 'sees-platform-cluster'
      ECS_TASK_DEFINITION: 'sees-platform-app'
      CONTAINER_NAME: 'app'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Run Prisma Migrations
      run: |
        # Automatically find the private subnet and security group created by Terraform
        export PRIVATE_SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=tag:Name,Values=sees-platform-private-subnet-0" --query 'Subnets[0].SubnetId' --output text)
        export ECS_SG_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=sees-platform-ecs-tasks-sg" --query 'SecurityGroups[0].GroupId' --output text)
        
        echo "Found Subnet: $PRIVATE_SUBNET_ID"
        echo "Found SG: $ECS_SG_ID"

        aws ecs run-task \
          --cluster $ECS_CLUSTER \
          --task-definition $ECS_TASK_DEFINITION \
          --overrides '{"containerOverrides": [{"name": "app", "command": ["npx", "prisma", "migrate", "deploy"]}]}' \
          --launch-type FARGATE \
          --network-configuration "{\"awsvpcConfiguration\": {\"subnets\": [\"$PRIVATE_SUBNET_ID\"], \"securityGroups\": [\"$ECS_SG_ID\"]}}" \
          --wait

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
